#!/bin/sh
#SBATCH --time=72:00:00
#SBATCH --partition=scavenger
#SBATCH --qos=scavenger
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=50
#SBATCH --job-name="mrta_att_mpi_stevepau"
#SBATCH --output=output_mrta_mpi.out
#SBATCH --error=error_mrta_mpi.err
#SBATCH --mail-user=stevepau@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --exclusive
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

echo "SLURM_SUBMIT_DIR="$SLURM_SUBMIT_DIR

module load python/py36-anaconda-5.2.0
module load intel-mpi
pip install --user mpi4py
pip install --user torch
#module load mpi4py
ulimit -s unlimited
#export PYTHONPATH= /util/academic/python/mpi4py/v2.0.0/lib/python2.7/site-packages:$PYTHONPATH
#export I_MPI_DEBUG=4
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export I_MPI_FABRICS_LIST=tcp
#source activate py27-mpi
#eval "$(/util/common/python/py37/anaconda-2020.02/bin/conda shell.bash hook)"
#conda activate pytorch-1.5-dgl
#conda install -p /home/stevepau tqdm
#conda activate tqdm
#
#CUDA_VISIBLE_DEVICES=0
#python run.py
mpiexec -n 50 python run_mpi.py
echo "***********************************************************************"


#
echo "All Done!"
